# Generated by Django 5.0.3 on 2024-03-08 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('delivery_method', models.CharField(choices=[('email', 'Email'), ('push', 'Push Notification')], max_length=20)),
                ('scheduled_datetime', models.DateTimeField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_interval', models.CharField(blank=True, max_length=20, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
