# Generated by Django 5.0.3 on 2024-03-19 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_remove_notification_id_notification_notifcation_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notifcation_id',
            new_name='notification_id',
        ),
    ]
