# Generated by Django 5.0.3 on 2024-07-06 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_rename_notifcation_id_notification_notification_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='delivery_method',
        ),
    ]
